
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    networks:
      - appnetwork

  graphql:
    build:
      context: .
      dockerfile: GraphQL/Dockerfile
    container_name: graphql
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=CommunicationDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080" # host:container
    networks:
      - appnetwork

  serverapp:
    build:
      context: .
      dockerfile: ServerApp/Dockerfile
    container_name: serverapp
    depends_on:
      - graphql
    environment:
      - GraphQL__BaseUrl=http://graphql:8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge
